spring:
data:
mongodb:
uri: mongodb://localhost:27017/smartgrid_billing
database: smartgrid_billing

spring:
kafka:
bootstrap-servers: localhost:9092
consumer:
group-id: billing-group
key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
properties:
spring.json.trusted.packages: '*'